Add JSON Path (#14)

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -28,7 +28,7 @@ jobs:
 
     steps:
       - name: "Checkout"
-        uses: actions/checkout@v5
+        uses: actions/checkout@v6
 
       - name: "Debug CTX github"
         if: ${{ !github.event.act }}
@@ -88,6 +88,29 @@ jobs:
             echo "Output Invalid"
             exit 1
           fi
+
+      - name: "3: Test Path"
+        if: ${{ !github.event.act }}
+        id: test3
+        uses: ./
+        with:
+          url: "https://pypi.org/pypi/toml_run/json"
+          method: "GET"
+          path: '$.urls[?(@.packagetype=="sdist")]'
+
+      - name: "3: Verify Path"
+        if: ${{ !github.event.act }}
+        run: |
+          echo 'status: ${{ steps.test3.outputs.status }}'
+          echo 'headers: ${{ steps.test3.outputs.headers }}'
+          echo 'data: ${{ steps.test3.outputs.data }}'
+          echo 'result: ${{ steps.test3.outputs.result }}'
+          if [ -z '${{ steps.test3.outputs.result }}' ];then
+            echo "Output Invalid: result"
+            exit 1
+          fi
+          echo 'url: ${{ fromJSON(steps.test3.outputs.result).url }}'
+          echo 'sha256: ${{ fromJSON(steps.test3.outputs.result).digests.sha256 }}'
 
       - name: "Schedule Failure Notification"
         if: ${{ failure() && github.event_name == 'schedule' }}
